---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-spring-boot-mongodb
  name: java-spring-boot-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-spring-boot-mongodb
  template:
    metadata:
      labels:
        app: java-spring-boot-mongodb
    spec:
      containers:
        - image: ykhadilkar/java-spring-boot-mongodb-starter
          name: java-spring-boot-mongodb

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-spring-boot-mongodb
  name: java-spring-boot-mongodb
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: java-spring-boot-mongodb
  sessionAffinity: None
  type: LoadBalancer